# Generated by Django 4.2.9 on 2026-06-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('capacity', models.IntegerField(default=0)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'halls',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('setup_start_at', models.DateTimeField()),
                ('teardown_end_at', models.DateTimeField()),
                ('total_seats', models.IntegerField(default=0)),
                ('sold_seats', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performances', to='tickets.hall')),
            ],
            options={
                'db_table': 'performances',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('troupe', models.CharField(blank=True, default='', max_length=128)),
                ('genre', models.CharField(choices=[('concert', '演唱会'), ('drama', '话剧'), ('musical', '音乐剧'), ('opera', '戏曲'), ('other', '其他')], default='concert', max_length=16)),
                ('status', models.CharField(choices=[('on_sale', '售票中'), ('upcoming', '待开票'), ('ended', '已结束')], default='upcoming', max_length=16)),
                ('duration_minutes', models.IntegerField(default=120)),
                ('setup_minutes', models.IntegerField(default=60)),
                ('teardown_minutes', models.IntegerField(default=30)),
                ('min_capacity', models.IntegerField(default=0)),
                ('required_facilities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shows',
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'theaters',
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('paid', '已支付'), ('cancelled', '已取消')], default='paid', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tickets.performance')),
            ],
            options={
                'db_table': 'ticket_orders',
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='tickets.show'),
        ),
        migrations.CreateModel(
            name='MaintenancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_periods', to='tickets.hall')),
            ],
            options={
                'db_table': 'maintenance_periods',
            },
        ),
        migrations.AddField(
            model_name='hall',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='tickets.theater'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['hall', 'start_at'], name='performance_hall_id_46d8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['show', 'start_at'], name='performance_show_id_b3c23e_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceperiod',
            index=models.Index(fields=['hall', 'start_at'], name='maintenance_hall_id_f95dc4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hall',
            unique_together={('theater', 'name')},
        ),
    ]
